// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Bikelife76 
//@version=6

library("Labuba_MajorCobraMetrics2025", overlay = true)

// @function Call function to get a certain curve of your strategy.
// @param What type of curve to plot. Example: Equity.
// @returns Returns type of curve plot.
export curve(string disp_ind) =>
    float x = switch disp_ind
        "Equity" => strategy.equity / strategy.initial_capital
        "Open Profit" => strategy.openprofit
        "Net Profit" => strategy.netprofit
        "Gross Profit" => strategy.grossprofit
        => na
        
	x
    
// @function Call function to filter out your Strategy plots
// @param Insert disp_ind variable and your strategy plot variable
export cleaner(string disp_ind, float plot) =>
    float y = 1.0
    y := disp_ind == "Strategy" ? plot : na

    y

maxEquityDrawDown() =>
    float max_dd = 0.0
    float max_eq = strategy.equity
    max_eq := math.max(nz(max_eq[1]), strategy.equity)
    max_dd := math.min(nz(max_dd[1]), strategy.equity / max_eq - 1)
    
    max_dd
   
maxTradeDrawDown() =>
    tradeEntryEquity = 0.0
    maxDrawdownPercent = 0.0
    for tradeNo = 0 to strategy.closedtrades-1
        maxDrawdownPercent := math.max(maxDrawdownPercent, (strategy.closedtrades.max_drawdown(tradeNo) / (math.abs(strategy.closedtrades.size(tradeNo)) * strategy.closedtrades.entry_price(tradeNo)) * 100))
    
    maxDrawdownPercent

consecutive_wins() =>
    consecutive_wins = 0
    cons_wins = 0
    for tradeNo = 0 to strategy.closedtrades-1
        if strategy.closedtrades.profit(tradeNo) > 0 
            cons_wins := cons_wins + 1
        if strategy.closedtrades.profit(tradeNo) < 0 
            cons_wins := 0
        consecutive_wins := math.max(consecutive_wins, cons_wins)
    
    consecutive_wins

consecutive_losses() =>
    consecutive_losses = 0
    cons_losses = 0
    for tradeNo = 0 to strategy.closedtrades-1
        if strategy.closedtrades.profit(tradeNo) < 0 
            cons_losses := cons_losses + 1
        if strategy.closedtrades.profit(tradeNo) > 0 
            cons_losses := 0
        consecutive_losses := math.max(consecutive_losses, cons_losses)
    
    consecutive_losses


no_position() =>
    var no_pos = 0
    var max_no_pos = 0
    if year > 2017
        if strategy.position_size == 0
            no_pos := no_pos + 1
            max_no_pos := math.max(no_pos, max_no_pos)
        if strategy.position_size != 0
            no_pos := 0

    max_no_pos

long_profit() =>
    long_profit = 0.0
    for tradeNo = 0 to strategy.closedtrades - 1
        if strategy.closedtrades.size(tradeNo) > 0
            long_profit := long_profit + (strategy.closedtrades.profit(tradeNo))
    result = long_profit / strategy.initial_capital * 100

    result

short_profit() =>
    short_profit = 0.0
    for tradeNo = 0 to strategy.closedtrades - 1
        if strategy.closedtrades.size(tradeNo) < 0
            short_profit := short_profit + (strategy.closedtrades.profit(tradeNo))
    result = short_profit / strategy.initial_capital * 100

    result

prev_month()=>
    var prev_month_profits = 0.0
    if dayofmonth == 1
        prev_month_profits := strategy.equity[1] - strategy.equity[dayofmonth[1] + 1]

    prev_month_profits

w_months() =>
    var win_months = 0
    if dayofmonth == 1 and prev_month() > 0
        win_months := win_months + 1

    win_months

l_months() =>
    var lose_months = 0
    if dayofmonth == 1 and prev_month() < 0
        lose_months := lose_months + 1

    lose_months

checktf() =>
    y = switch timeframe.period
        "M" => 365 / 30
        "10D" => 365 / 10
        "9D" => 365 / 9
        "8D" => 365 / 8
        "W" => 365 / 7
        "6D" => 365 / 6
        "5D" => 365 / 5
        "4D" => 365 / 4
        "3D" => 365 / 3
        "2D" => 365 / 2
        "D" => 365
        "720" => 365 * 2
        "480" => 365 * 3
        "240" => 365 * 6
        "60" => 365 * 24
        => 365

    y

stat_calc() =>
    float daily_return = strategy.equity / strategy.equity[1] - 1
    var returns_array = array.new_float(0)
    var negative_returns_array = array.new_float(0)
    var positive_returns_array = array.new_float(0)

    if year > 2017
        array.push(returns_array, daily_return)
        if daily_return <= 0.0
            array.push(negative_returns_array, daily_return)
        else
            array.push(positive_returns_array, daily_return)

    ////STAT CALCULATIONS
    equity_drawdown = math.round(maxEquityDrawDown() * 100, 2)
    intrade_drawdown = math.round(maxTradeDrawDown()*(-1),2)
    standard_deviation = array.stdev(returns_array)
    negative_returns_standard_deviation = array.stdev(negative_returns_array)
    mean = array.avg(returns_array)
    sharpe = math.round(mean / standard_deviation * math.sqrt(checktf()), 2)
    sortino = math.round(mean / negative_returns_standard_deviation * math.sqrt(checktf()), 2)
    postive_area = array.sum(positive_returns_array)
    negative_area = array.sum(negative_returns_array) * (-1)
    omega = math.round(postive_area / negative_area, 2)
    trades = strategy.closedtrades
    profitable_percent = math.round(strategy.wintrades / trades * 100, 2)
    profit_factor = math.round(strategy.grossprofit / strategy.grossloss, 2)
    consecutive_win = consecutive_wins()
    consecutive_loss = consecutive_losses()
    long_total_profit = math.round(long_profit(), 2)
    short_total_profit = math.round(short_profit(), 2)
    total_winning_months = w_months()
    total_losing_months = l_months()
    net_profit_ls_ratio = math.round(long_total_profit < 0 or short_total_profit < 0 ? 0 : long_total_profit > short_total_profit ? long_total_profit / short_total_profit : short_total_profit / long_total_profit, 2)
    netprofit = math.round(strategy.netprofit / (strategy.initial_capital / 100), 2)

    [equity_drawdown, intrade_drawdown, sharpe, sortino, omega, trades, profitable_percent, profit_factor, consecutive_win, consecutive_loss, total_winning_months, total_losing_months, net_profit_ls_ratio, netprofit]

////SLAPPER PARAMETERS
var intrade_dd_slap_value = -25
var intrade_dd_low_value = -40
var sharpe_slap_value = 2.
var sharpe_low_value = 1.
var sortino_slap_value = 2.9
var sortino_low_value = 2.
var trades_slap_value = 45
var trades_low_value = 40
var trades_high_value = 105
var profitable_slap_value = 50
var profitable_low_value = 35
var profit_factor_slap_value = 4.
var profit_factor_low_value = 2.
var omega_high_value = 1.31
var omega_low_value = 1.1

f_colors(string x, float nv) =>
    var color col_up = color.rgb(0, 255, 8, 50)
    var color col_neutral = color.rgb(243, 251, 3, 31)
    var color col_down = color.rgb(255, 0, 0, 50)
    var color out = na

    var lowtrades = trades_low_value
    var hightrades = trades_high_value
    switch timeframe.period
        "D" => lowtrades := 45, hightrades := 105
        "720" => lowtrades := 60, hightrades := 200
        "480" => lowtrades := 200, hightrades := 540
        "60" => lowtrades := 300, hightrades := 800
        => lowtrades := 45, hightrades := 105

    switch x
        "𝐄𝐪𝐮𝐢𝐭𝐲 𝐌𝐚𝐱 𝐃𝐃" => out := nv >= intrade_dd_slap_value ? col_up : nv >= intrade_dd_low_value ? col_neutral : col_down

        "𝐈𝐧𝐭𝐫𝐚-𝐭𝐫𝐚𝐝𝐞 𝐌𝐚𝐱 𝐃𝐃" => out := nv >= intrade_dd_slap_value ? col_up : nv >= intrade_dd_low_value ? col_neutral : col_down
        
        "𝐒𝐨𝐫𝐭𝐢𝐧𝐨 𝐑𝐚𝐭𝐢𝐨" => out := nv >= sortino_slap_value ? col_up : nv >= sortino_low_value ? col_neutral : col_down
        
        "𝐒𝐡𝐚𝐫𝐩𝐞 𝐑𝐚𝐭𝐢𝐨" => out := nv >= sharpe_slap_value ? col_up : nv >= sharpe_low_value ? col_neutral : col_down
    
        "𝐏𝐫𝐨𝐟𝐢𝐭 𝐅𝐚𝐜𝐭𝐨𝐫" => out := nv >= profit_factor_slap_value ? col_up : nv >= profit_factor_low_value ? col_neutral : col_down
        
        "𝐏𝐫𝐨𝐟𝐢𝐭𝐚𝐛𝐥𝐞 %" => out := nv >= profitable_slap_value ? col_up : nv >= profitable_low_value ? col_neutral : col_down
    
        
        "𝐎𝐦𝐞𝐠𝐚 𝐑𝐚𝐭𝐢𝐨 Ω" => out := nv >= omega_high_value ? col_up : nv >= omega_low_value ? col_neutral : col_down
        
        "𝐓𝐫𝐚𝐝𝐞𝐬" => out := nv >= lowtrades and nv <= hightrades ? col_up : nv >= 40 and nv <= 105 ? col_neutral : col_down


        "𝐍𝐞𝐭 𝐏𝐫𝐨𝐟𝐢𝐭 𝐋/𝐒 𝐑𝐚𝐭𝐢𝐨" => out := nv >= 1 and nv <= 2 ? col_up : nv > 2 and nv <= 3 ? col_neutral : col_down

        => out := color.new(#000000, 0)
        
    out




// @function Assign this function to a random variable to get the "Performance Table"
export cobraTable(simple string option = "Full", simple string position = "Middle Right") =>
    var pos = switch position
        "Top Left" => position.top_left
        "Middle Left" => position.middle_left
        "Bottom Left" => position.bottom_left
        "Top Right" => position.top_right
        "Middle Right" => position.middle_right
        "Bottom Right" => position.bottom_right
        "Top Center" => position.top_center
        "Bottom Center" => position.bottom_center

    var table Main = table.new(pos, 2, 17, border_width = 1, frame_width = 1, frame_color = color.white)
    
    [equity_drawdown, intrade_drawdown, sharpe, sortino, omega, trades, profitable_percent, profit_factor, consecutive_win, consecutive_loss, total_winning_months, total_losing_months, net_profit_ls_ratio, netprofit] = stat_calc()
    
    lowtrades = trades_low_value
    hightrades = trades_high_value
    switch timeframe.period
        "D" => lowtrades := 45, hightrades := 105
        "720" => lowtrades := 60, hightrades := 200
        "480" => lowtrades := 200, hightrades := 540
        "60" => lowtrades := 300, hightrades := 800
        => lowtrades := 45, hightrades := 105

    int slap_score = 0
    slap_score += intrade_drawdown >= intrade_dd_slap_value ? 1 : intrade_drawdown <= intrade_dd_low_value ? 0 : 0
    slap_score += equity_drawdown >= intrade_dd_slap_value ? 1 : equity_drawdown <= intrade_dd_low_value ? 0: 0
    slap_score += sharpe >= sharpe_slap_value ? 1 : sharpe <= sharpe_low_value ? 0: 0
    slap_score += sortino >= sortino_slap_value ? 1 : sortino <= sortino_low_value ? 0: 0
    slap_score += trades >= lowtrades and trades <= hightrades ? 1 : trades < lowtrades or trades > hightrades ? 0 : 0
    slap_score += profitable_percent >= profitable_slap_value ? 1 : profitable_percent <= profitable_low_value ? 0 : 0
    slap_score += profit_factor >= profit_factor_slap_value ? 1 : profit_factor <= profit_factor_low_value ? 0 : 0
    slap_score += omega >= omega_high_value ? 1 : omega <= omega_low_value ? 0 : 0

    switch option
        "Full" =>
            for i = 0 to 16
                [name, value] = switch i
                    0 => ["🐍 𝓒𝓸𝓫𝓻𝓪 𝓜𝓮𝓽𝓻𝓲𝓬𝓼 🐍", na]
                    1 => ["𝐄𝐪𝐮𝐢𝐭𝐲 𝐌𝐚𝐱 𝐃𝐃", equity_drawdown]
                    2 => ["𝐈𝐧𝐭𝐫𝐚-𝐭𝐫𝐚𝐝𝐞 𝐌𝐚𝐱 𝐃𝐃", intrade_drawdown]
                    3 => ["𝐒𝐨𝐫𝐭𝐢𝐧𝐨 𝐑𝐚𝐭𝐢𝐨", sortino]
                    4 => ["𝐒𝐡𝐚𝐫𝐩𝐞 𝐑𝐚𝐭𝐢𝐨", sharpe]
                    5 => ["𝐏𝐫𝐨𝐟𝐢𝐭 𝐅𝐚𝐜𝐭𝐨𝐫", profit_factor]
                    6 => ["𝐏𝐫𝐨𝐟𝐢𝐭𝐚𝐛𝐥𝐞 %", profitable_percent]
                    7 => ["𝐓𝐫𝐚𝐝𝐞𝐬", trades]
                    8 => ["𝐎𝐦𝐞𝐠𝐚 𝐑𝐚𝐭𝐢𝐨 Ω", omega]
                    9 => ["𝐍𝐞𝐭 𝐏𝐫𝐨𝐟𝐢𝐭 %", netprofit]
                    10 => ["𝐍𝐞𝐭 𝐏𝐫𝐨𝐟𝐢𝐭 𝐋/𝐒 𝐑𝐚𝐭𝐢𝐨", net_profit_ls_ratio]
                    11 => ["𝐌𝐚𝐱 𝐂𝐨𝐧𝐬𝐞𝐜𝐮𝐭𝐢𝐯𝐞 𝐖𝐢𝐧𝐬", consecutive_win]
                    12 => ["𝐌𝐚𝐱 𝐂𝐨𝐧𝐬𝐞𝐜𝐮𝐭𝐢𝐯𝐞 𝐋𝐨𝐬𝐬𝐞𝐬", consecutive_loss]
                    13 => ["𝐌𝐚𝐱 𝐅𝐥𝐚𝐭 𝐃𝐚𝐲𝐬", no_position()]
                    14 => ["𝐓𝐨𝐭𝐚𝐥 𝐦𝐨𝐧𝐭𝐡𝐬 𝐢𝐧 𝐩𝐫𝐨𝐟𝐢𝐭", total_winning_months]
                    15 => ["𝐓𝐨𝐭𝐚𝐥 𝐦𝐨𝐧𝐭𝐡𝐬 𝐢𝐧 𝐥𝐨𝐬𝐬", total_losing_months]
                    16 => [str.format("{0}/7", slap_score), na]

                table.cell(Main, 0, i, name, bgcolor = color.new(#000000, 0), text_color = #0162fe, text_halign = text.align_left, text_font_family = font.family_monospace)
                table.cell(Main, 1, i, str.tostring(value) + (i == 1 or i == 2 or i == 6 or i == 9 ? " %" : na), bgcolor = f_colors(name, value), text_color = color.rgb(255, 255, 255), text_halign = text.align_right, text_font_family = font.family_monospace)

            table.merge_cells(Main, 0, 0, 1, 0), table.cell_set_text_halign(Main, 0, 0, text.align_center)
            table.merge_cells(Main, 0, 16, 1, 16), table.cell_set_text_halign(Main, 0, 16, text.align_center)

        "Simple" =>
            for i = 0 to 9
                [name, value] = switch i
                    0 => ["🐍 𝓒𝓸𝓫𝓻𝓪 𝓜𝓮𝓽𝓻𝓲𝓬𝓼 🐍", na]
                    1 => ["𝐈𝐧𝐭𝐫𝐚-𝐭𝐫𝐚𝐝𝐞 𝐌𝐚𝐱 𝐃𝐃", intrade_drawdown]
                    2 => ["𝐒𝐨𝐫𝐭𝐢𝐧𝐨 𝐑𝐚𝐭𝐢𝐨", sortino]
                    3 => ["𝐒𝐡𝐚𝐫𝐩𝐞 𝐑𝐚𝐭𝐢𝐨", sharpe]
                    4 => ["𝐏𝐫𝐨𝐟𝐢𝐭 𝐅𝐚𝐜𝐭𝐨𝐫", profit_factor]
                    5 => ["𝐏𝐫𝐨𝐟𝐢𝐭𝐚𝐛𝐥𝐞 %", profitable_percent]
                    6 => ["𝐓𝐫𝐚𝐝𝐞𝐬", trades]
                    7 => ["𝐎𝐦𝐞𝐠𝐚 𝐑𝐚𝐭𝐢𝐨 Ω", omega]
                    8 => ["𝐍𝐞𝐭 𝐏𝐫𝐨𝐟𝐢𝐭 %", netprofit]
                    9 => [str.format("{0}/7", slap_score), na]

                table.cell(Main, 0, i, name, bgcolor = color.new(#000000, 0), text_color = #0162fe, text_halign = text.align_left, text_font_family = font.family_monospace)
                table.cell(Main, 1, i, str.tostring(value) + (i == 1 or i == 5 or i == 8 ? " %" : na), bgcolor = f_colors(name, value), text_color = color.rgb(255, 255, 255), text_halign = text.align_right, text_font_family = font.family_monospace)

            table.merge_cells(Main, 0, 0, 1, 0), table.cell_set_text_halign(Main, 0, 0, text.align_center)
            table.merge_cells(Main, 0, 9, 1, 9), table.cell_set_text_halign(Main, 0, 9, text.align_center)

        "None" => table.delete(Main)

    Main

str = input.string("Full", "Type", options = ["Simple", "Full", "None"])
st = cobraTable(str, "Middle Right")

