//@version=6
indicator("RSI Convergence Divergence | JOUUURJE", shorttitle = "RSICD | JOUUURJE",overlay=false)

ma(source, length, type) =>
    switch type
        "SMA" => ta.sma(source, length)
        "EMA" => ta.ema(source, length)
        "SMMA" => ta.rma(source, length)
        "WMA" => ta.wma(source, length)
        "VWMA" => ta.vwma(source, length)
        "TEMA" =>
            ema1 = ta.ema(source, length)
            ema2 = ta.ema(ema1, length)
            ema3 = ta.ema(ema2, length)
            3 * (ema1 - ema2) + ema3
        "DEMA" =>
            ema1 = ta.ema(source, length)
            ema2 = ta.ema(ema1, length)
            2 * ema1 - ema2
        "LSMA" => ta.linreg(source, length, 0)
        "HMA" => ta.wma(2 * ta.wma(source, length / 2) - ta.wma(source, length), math.floor(math.sqrt(length)))
        "ALMA" => ta.alma(source, length, 0.85, 6)

gaussian_filter(src, length, sigma) =>
    gaussian_sum = 0.0
    gaussian_weighted_sum = 0.0
    for i = 0 to length - 1 by 1
        weight = math.exp(-0.5 * math.pow((i - (length - 1) / 2) / sigma, 2))
        gaussian_sum := gaussian_sum + weight
        gaussian_weighted_sum := gaussian_weighted_sum + src[i] * weight
        gaussian_weighted_sum
    gaussian_weighted_sum / gaussian_sum

// === Inputs ===

rsiLength = input.int(40, "RSI Length", minval=1)

maLength = input.int(33, "Moving Average Length", minval = 1)
maType = input.string("SMMA", "Moving Average Type", options = ["SMA", "EMA", "SMMA", "WMA", "VWMA", "TEMA", "DEMA", "LSMA", "HMA", "ALMA"])

upperThreshold = input.float(1.69, "Upper Threshold", step = 0.01)
lowerThreshold = input.float(-0.61, "Lower Threshold", step = 0.01)

useGaussian = input.bool(false, "Use Gaussian Filter")

inputSrc = input.source(close, "Source")

src = useGaussian ? gaussian_filter(math.log(inputSrc), input.int(6, "Gaussian Filter Length", minval = 1), 2.0) : math.log(inputSrc)

rsi = ta.rsi(src, rsiLength)
rsiMA = ma(rsi, maLength, maType)

rsiscore = rsi-rsiMA

signalColor = color.gray
JOUUURJE = 0
if rsiscore > upperThreshold
    signalColor := color.lime
    JOUUURJE := 1
else if rsiscore < lowerThreshold
    signalColor := color.red
    JOUUURJE := -1
else
    signalColor := signalColor[1]
    JOUUURJE := JOUUURJE[1]

// === Plot the Score ===
plot(rsiscore, title="RSI Z-Score", color=signalColor, linewidth=1)
plot(upperThreshold, "Upper Threshold", color.lime)
plot(lowerThreshold, "Upper Threshold", color.red)
hline(0, "Neutral", color=color.gray)


plotcandle(open, high, low, close, color = signalColor, bordercolor = signalColor, wickcolor = signalColor, force_overlay = true, display = display.all - display.status_line)
